version: '3.7'

services:
  mysql:
    container_name: codeflix_admin_catalog_mysql
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=adm_videos
    security_opt:
      - seccomp:unconfined
    ports:
      - 3306:3306
    networks:
      -   codeflix_admin_catalog_network

networks:
  codeflix_admin_catalog_network: